---
title: "atlas"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{atlas}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ape)
library(phylobar)
library(microbiome)
```

```{r}
data(atlas1006)
pseq3 <- atlas1006 |>
  subset_samples(DNA_extraction_method == "r") |>
  transform(transform = "compositional")
```

A naive tree construction would have loops!

```{r}
tree <- taxonomy_to_tree(tax_table(pseq3))
ape::checkValidPhylo(tree)
```

We can add prefixes.

```{r}
taxa <- tax_table(pseq3)
taxa <- cbind(Kingdom = "Bacteria", taxa)
taxa <- add_prefix(taxa)

tree <- taxonomy_to_tree(taxa)
ape::checkValidPhylo(tree)
```

```{r}
x <- t(otu_table(pseq3))
phylobar(x, tree, sample_show_all = FALSE, rel_width = 0.2)
```

We could subsample if we want a slightly simpler plot. Most of the conclusions
remain the same.

```{r}
x_sub <- subset_cluster(x)
x_sub <- x_sub[, colSums(x_sub) > 0]

leaves_to_keep <- intersect(tree$tip.label, colnames(x_sub))
filtered_tree <- drop.tip(tree, setdiff(tree$tip.label, leaves_to_keep))
phylobar(x_sub, filtered_tree)
```