---
title: "hfhs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hfhs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
library(phylobar)
library(LUPINE)
library(dplyr)
library(ape)
library(stringr)
```

```{r}
data(HFHSdata)
normal <- HFHSdata$OTUdata_Normal
taxa <- HFHSdata$filtered_taxonomy
```

Let's construct a tree from the taxonomy and make sure it's valid.

```{r}
tree <- taxa |>
    select(-X1, X1) |>
    mutate(
        across(
            everything(), 
            ~if_else(str_ends(., "_"), NA, .)
        )
    ) |>
    taxonomy_to_tree()

checkValidPhylo(tree)
```

Let's manually reorder to reflect time and host at time 0.

```{r}
comp0 <- normal[,, 1]
comp0 <- comp0 / rowSums(comp0)
sample_order <- hclust(dist(comp0))$order
species_order <- hclust(dist(t(comp0)))$order
```

Now we can melt the tensor.

```{r}
x <- normal[sample_order, species_order, ] |>
    aperm(c(3, 1, 2)) |>
    matrix(nrow = dim(normal)[3] * nrow(normal), ncol = ncol(normal))

rownames(x) <- apply(
    expand.grid(rownames(normal)[sample_order], c(0, 1, 4, 7)),
    1, paste, collapse = "-"
)
```

Finally we convert to compositions and visualize.

```{r}
comp <- x / rowSums(x)
colnames(comp) <- colnames(normal)[species_order]
phylobar(comp, tree, hclust_order = FALSE)
```
```{r}
sessionInfo()
```