---
title: "Oral Cancer Microbiome"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Oral Cancer Microbiome}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    warning = FALSE,
    message = FALSE
)
```

```{r setup}
library(phylobar)
library(ape)
library(tidyverse)
```

In this step ...

```{r, read_in_data}
ps <- readRDS("vignettes/zhang2023-ps.rds")
```

```{r}
x_mat <- t(otu_table(ps))
x_mat <- x_mat / rowSums(x_mat)
x_mat <- subset_cluster(x_mat, k = 100)
```

```{r}`
sample_order <- data.frame(sample_data(ps)) |>
  rownames_to_column("sample") |>
  group_by(id) |>
  mutate(mean_mucositis = mean(mucositis)) |>
  ungroup() |>
  arrange(mean_mucositis, timepoint) |>
  pull(sample)
```

```{r}
# Order rowas and columns using data above.
row_ix <- sample_order[sample_order %in% rownames(x_mat)]
col_ix <- hclust(dist(t(x_mat)))$order
```

```{r}
phylobar(
  x_mat[row_ix, col_ix],
  phy_tree(ps),
  width = 900,
  sample_show_all = FALSE,
  hclust_order = FALSE,
  sample_label_space = 75
)
```

### Streamgraph Visualization

```{r}
smooth_time_series <- function(df, time_col = "timepoint", pseudocount = 1, round_degree = 2, bandwidth = 5) {
    # Round timepoints
    df <- df |>
        mutate(time_bin = round_degree * round(.data[[time_col]] / round_degree)) |>
        arrange(time_bin) |>
        group_by(time_bin) |>
        summarise(
            value = (sum(value) + pseudocount) / (n() + pseudocount)
        )
    
    # Fill gaps with 0
    tibble(time_bin = seq(min(df$time_bin), max(df$time_bin), by = round_degree)) |>
        left_join(df, by = "time_bin") |>
        mutate(value = replace_na(value, 0)) |>
        reframe(
            smooth_value = ksmooth(time_bin, value, "normal", bandwidth, n.points = n())$y,
            time_bin = ksmooth(time_bin, value, "normal", bandwidth, n.points = n())$x
        )
}
```

```{r}
x_mat <- t(otu_table(ps)) |>
    data.frame() |>
    rownames_to_column("sample")
metadata <- sample_data(ps) |>
    data.frame() |>
    rownames_to_column("sample") |>
    left_join(mucositis)
```

```{r}
x_long_format <- x_mat |>
    left_join(metadata, by = "sample") |>
    filter(between(timepoint, -5, 55)) |>
    select(id, timepoint, mean_mucositis, starts_with("OTU")) |>
    pivot_longer(starts_with("O"), names_to = "feature", values_to = "value")

x_smooth <- x_long_format |>
    group_by(feature, severity = if_else(mean_mucositis > 3.5, "S", "NS")) |>
    group_modify(~ smooth_time_series(.x)) |>
    unite(row, time_bin, severity, sep = "") |>
    pivot_wider(names_from = feature, values_from = smooth_value) |>
    column_to_rownames("row")
```

## Phylobar Visualization

```{r}
x_smooth <- x_smooth / rowSums(x_smooth)
phylobar(
  x_smooth, 
  phy_tree(ps), 
  width = 900, 
  hclust_order = FALSE
)
```

```{r}
sessionInfo()
```